name: builder EC2 CD

on:
  workflow_run:
    workflows: ["Builder Docker Image"]
    types:
      - completed

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | sudo docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          
      - name: Create Docker Network
        run: |
          if ! sudo docker network ls | grep -q oauth-network; then
            sudo docker network create oauth-network
          fi
      
      - name: Run Redis container
        run: |
          sudo docker run -d \
          --name oauth-redis-container \
          --network oauth-network \
          -p 6379:6379 \
          redis:latest

      - name: Pull Docker image
        run: sudo docker pull saheersk/oauth:latest

      - name: Run Docker container
        env:
          REDIS_HOST: ${{ secrets.REDIS_HOST }}
          HUBSPOT_CLIENT_ID: ${{ secrets.HUBSPOT_CLIENT_ID}}
          HUBSPOT_CLIENT_SECRET: ${{ secrets.HUBSPOT_CLIENT_SECRET }}
          AIRTABLE_CLIENT_ID: ${{ secrets.AIRTABLE_CLIENT_ID }}
          AIRTABLE_CLIENT_SECRET: ${{ secrets.AIRTABLE_CLIENT_SECRET }}
          NOTION_CLIENT_ID: ${{ secrets.NOTION_CLIENT_ID }}
          NOTION_CLIENT_SECRET: ${{ secrets.NOTION_CLIENT_SECRET }}
        run: |
          sudo docker run -d \
          -p 8000:8000 \
          --name oauth-container \
          --network oauth-network \
          -e HUBSPOT_CLIENT_ID=$HUBSPOT_CLIENT_ID \
          -e HUBSPOT_CLIENT_SECRET=$HUBSPOT_CLIENT_SECRET \
          -e AIRTABLE_CLIENT_ID=$AIRTABLE_CLIENT_ID \
          -e AIRTABLE_CLIENT_SECRET=$AIRTABLE_CLIENT_SECRET \
          -e NOTION_CLIENT_ID=$NOTION_CLIENT_ID \
          -e NOTION_CLIENT_SECRET=$NOTION_CLIENT_SECRET \
          -e REDIS_HOST=$REDIS_HOST \
          saheersk/oauth
